#!/bin/bash
sudo apt-get install exuberant-ctags
sudo apt-get install exuberant-ctags

find . -name "*.c" -o -name "*.h" -o -name "*.hpp" > cscope.files
cscope -qRbi cscope.files
ctags -RL cscope.files
